const express=require('express');
const cors=require('cors');
const crypto=require('crypto');
const {promisify}=require('util');
const {neon}=require('@neondatabase/serverless');
const app=express(),scrypt=promisify(crypto.scrypt),allowed=new Set(['https://microsatoshi.wapka.top','https://microsatoshi-backend.vercel.app']);
app.disable('x-powered-by');app.set('trust proxy',1);app.use(cors({origin:(o,cb)=>cb(null,!o||allowed.has(o)),credentials:true}));app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');next()});app.use(express.json({limit:'32kb'}));
const db=()=>{if(!process.env.DATABASE_URL)throw Error('DATABASE_URL belum dikonfigurasi');return neon(process.env.DATABASE_URL)};
let rateCleanupCounter=0;
const limit=(name,windowMs=9e5,max=20)=>(req,res,next)=>{(async()=>{try{await ensureSchema();const address=String(req.ip||(req.socket&&req.socket.remoteAddress)||'unknown').slice(0,200);const keyHash=crypto.createHmac('sha256',process.env.DATABASE_URL).update(address).digest('hex');const q=db();const rows=await q`INSERT INTO auth_rate_limits(bucket,key_hash,request_count,reset_at) VALUES(${name},${keyHash},1,now()+(${windowMs}::double precision*interval '1 millisecond')) ON CONFLICT(bucket,key_hash) DO UPDATE SET request_count=CASE WHEN auth_rate_limits.reset_at<=now() THEN 1 ELSE auth_rate_limits.request_count+1 END,reset_at=CASE WHEN auth_rate_limits.reset_at<=now() THEN now()+(${windowMs}::double precision*interval '1 millisecond') ELSE auth_rate_limits.reset_at END RETURNING request_count,reset_at`;const row=rows[0];rateCleanupCounter++;if(rateCleanupCounter%100===0){try{await q`DELETE FROM auth_rate_limits WHERE reset_at<now()-interval '1 day'`}catch(_){}}if(Number(row.request_count)>max){const retry=Math.max(1,Math.ceil((new Date(row.reset_at).getTime()-Date.now())/1000));res.setHeader('Retry-After',String(retry));return res.status(429).json({error:'Terlalu banyak percobaan. Coba lagi nanti.'})}return next()}catch(_){return res.status(503).json({error:'Layanan autentikasi sementara tidak tersedia'})}})()};
let schema;
async function ensureSchema(){if(!schema){const sql=db();schema=(async()=>{await sql`CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS profiles (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,display_name TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS balances (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,amount NUMERIC(20,8) NOT NULL DEFAULT 0 CHECK(amount>=0),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS miners (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,active BOOLEAN NOT NULL DEFAULT false,updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS referrals (user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,code TEXT NOT NULL UNIQUE,referred_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS ledger_entries (id BIGSERIAL PRIMARY KEY,transaction_id TEXT NOT NULL UNIQUE,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,entry_type TEXT NOT NULL,amount NUMERIC(20,8) NOT NULL CHECK(amount<>0),balance_after NUMERIC(20,8) NOT NULL CHECK(balance_after>=0),metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE INDEX IF NOT EXISTS ledger_entries_user_created_idx ON ledger_entries(user_id,created_at DESC)`;await sql`CREATE TABLE IF NOT EXISTS idempotency_keys (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,request_key TEXT NOT NULL,operation TEXT NOT NULL,response JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),expires_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(user_id,request_key),CHECK(length(request_key) BETWEEN 8 AND 128))`;await sql`CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS auth_rate_limits (bucket TEXT NOT NULL,key_hash TEXT NOT NULL,request_count INTEGER NOT NULL DEFAULT 0 CHECK(request_count>=0),reset_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(bucket,key_hash))`;await sql`CREATE INDEX IF NOT EXISTS auth_rate_limits_reset_idx ON auth_rate_limits(reset_at)`})().catch(e=>{schema=null;throw e})}return schema}
const validEmail=v=>typeof v==='string'&&(()=>{const p=v.trim().split('@');return p.length===2&&p[0]&&p[1].includes('.')&&!p[1].startsWith('.')&&!p[1].endsWith('.')})();const validUser=v=>typeof v==='string'&&/^[A-Za-z0-9_]{3,32}$/.test(v);
async function hash(p){const salt=crypto.randomBytes(16).toString('hex');return `scrypt$${salt}$${(await scrypt(p,salt,64)).toString('hex')}`};async function verify(p,stored){const x=String(stored).split('$');if(x.length!==3||x[0]!=='scrypt')return false;const d=await scrypt(p,x[1],64),e=Buffer.from(x[2],'hex');return e.length===d.length&&crypto.timingSafeEqual(e,d)}
const cookie=(req,n)=>{try{const x=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(n+'='));return x?decodeURIComponent(x.slice(n.length+1)):null}catch(_){return null}};const th=t=>crypto.createHash('sha256').update(t).digest('hex');const setCookie=(res,t)=>res.setHeader('Set-Cookie',`ms_session=${encodeURIComponent(t)}; HttpOnly; Secure; SameSite=None; Partitioned; Path=/; Max-Age=604800`);
async function user(req){await ensureSchema();const t=cookie(req,'ms_session');if(!t)return null;const rows=await db()`SELECT u.id,u.username,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${th(t)} AND s.expires_at>now()`;return rows[0]||null}
const stagingPage='<!doctype html><html lang="id"><head><meta charset="utf-8"><title>MicroSatoshi Staging</title></head><body><h1>MicroSatoshi Staging</h1><p>Neon backend connected. Payment dan withdrawal nonaktif.</p></body></html>';
app.get('/staging',(req,res)=>res.type('html').send(stagingPage));app.get('/',(req,res)=>res.json({ok:true,service:'microsatoshi',mode:'vercel-neon-staging'}));app.get('/health',async(req,res)=>{try{await ensureSchema();await db()`SELECT 1`;res.json({ok:true,service:'microsatoshi',database:'connected'})}catch(_){res.status(503).json({ok:false,service:'microsatoshi',database:'unavailable'})}});
app.post('/register',limit('register'),async(req,res)=>{const body=req.body||{},ru=body.username,re=body.email,p=body.password,u=typeof ru==='string'?ru.trim():ru,e=typeof re==='string'?re.trim().toLowerCase():re;if(!validUser(u)||!validEmail(e)||typeof p!=='string'||p.length<8||p.length>128)return res.status(400).json({error:'Data pendaftaran tidak valid'});try{await ensureSchema();const q=db(),ph=await hash(p),rows=await q`WITH new_user AS (INSERT INTO users(username,email,password_hash) VALUES(${u},${e},${ph}) RETURNING id,username,email),new_profile AS (INSERT INTO profiles(user_id,display_name) SELECT id,username FROM new_user RETURNING user_id),new_balance AS (INSERT INTO balances(user_id) SELECT id FROM new_user RETURNING user_id),new_miner AS (INSERT INTO miners(user_id) SELECT id FROM new_user RETURNING user_id),new_referral AS (INSERT INTO referrals(user_id,code) SELECT id,'ms_'||id::text FROM new_user RETURNING user_id),new_audit AS (INSERT INTO audit_log(user_id,action) SELECT id,'register' FROM new_user RETURNING id) SELECT id,username,email FROM new_user`;res.status(201).json({ok:true,user:rows[0]})}catch(x){if(x&&x.code==='23505')return res.status(409).json({error:'Nama pengguna atau email sudah terdaftar'});res.status(500).json({error:'Pendaftaran gagal'})}});
app.post('/login',limit('login'),async(req,res)=>{const body=req.body||{},rl=body.login,p=body.password,l=typeof rl==='string'?rl.trim():rl;if(typeof l!=='string'||typeof p!=='string')return res.status(400).json({error:'Login tidak valid'});try{await ensureSchema();const q=db(),rows=await q`SELECT id,username,email,password_hash FROM users WHERE username=${l} OR email=${l.toLowerCase()} LIMIT 1`;if(!rows[0]||!(await verify(p,rows[0].password_hash)))return res.status(401).json({error:'Nama pengguna atau kata sandi salah'});const t=crypto.randomBytes(32).toString('hex');await q`DELETE FROM sessions WHERE expires_at<=now()`;await q`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(${th(t)},${rows[0].id},now()+interval '7 days')`;setCookie(res,t);res.json({ok:true,user:{id:rows[0].id,username:rows[0].username,email:rows[0].email}})}catch(_){res.status(500).json({error:'Login gagal'})}});
app.get('/me',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});res.json({ok:true,user:u})}catch(_){res.status(500).json({error:'Tidak dapat membaca sesi'})}});app.get('/balance',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const x=await db()`SELECT amount,updated_at FROM balances WHERE user_id=${u.id}`;res.json({ok:true,balance:x[0]||{amount:0}})}catch(_){res.status(500).json({error:'Saldo belum tersedia'})}});
app.get('/referral',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const q=db(),x=await q`SELECT code FROM referrals WHERE user_id=${u.id}`,n=await q`SELECT COUNT(*)::int AS total FROM referrals WHERE referred_by=${u.id}`;res.json({ok:true,enabled:false,code:(x[0]&&x[0].code)||null,registered:(n[0]&&n[0].total)||0,bonus:'0.00000000'})}catch(_){res.status(500).json({error:'Referral belum tersedia'})}});
app.get('/profile',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const x=await db()`SELECT display_name,created_at FROM profiles WHERE user_id=${u.id}`;res.json({ok:true,profile:x[0]||{display_name:u.username}})}catch(_){res.status(500).json({error:'Profil belum tersedia'})}});app.post('/profile',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const body=req.body||{},n=typeof body.display_name==='string'?body.display_name.trim():'';if(n.length>50)return res.status(400).json({error:'Nama tampilan terlalu panjang'});const q=db(),x=await q`UPDATE profiles SET display_name=${n||u.username} WHERE user_id=${u.id} RETURNING display_name,created_at`;await q`INSERT INTO audit_log(user_id,action) VALUES(${u.id},'profile_update')`;res.json({ok:true,profile:x[0]})}catch(_){res.status(500).json({error:'Profil tidak dapat disimpan'})}});
app.get('/miner',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const x=await db()`SELECT active,updated_at FROM miners WHERE user_id=${u.id}`;res.json({ok:true,miner:x[0]||{active:false}})}catch(_){res.status(500).json({error:'Status mining belum tersedia'})}});app.get('/activity',async(req,res)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});const x=await db()`SELECT action,created_at FROM audit_log WHERE user_id=${u.id} ORDER BY created_at DESC LIMIT 20`;res.json({ok:true,items:x})}catch(_){res.status(500).json({error:'Aktivitas belum tersedia'})}});
app.get('/history',async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:'Perlu masuk'});res.json({ok:true,enabled:false,items:[]})});app.post('/logout',async(req,res)=>{try{const t=cookie(req,'ms_session');if(t)await db()`DELETE FROM sessions WHERE token_hash=${th(t)}`;res.setHeader('Set-Cookie','ms_session=; HttpOnly; Secure; SameSite=None; Partitioned; Path=/; Max-Age=0');res.json({ok:true})}catch(_){res.status(500).json({error:'Logout gagal'})}});app.all('/payments',(req,res)=>res.status(403).json({error:'Payment masih dinonaktifkan untuk staging'}));app.all('/withdrawals',(req,res)=>res.status(403).json({error:'Withdrawal masih dinonaktifkan untuk staging'}));app.use((e,req,res,next)=>{if(e&&(e instanceof SyntaxError||e.status===400||e.type==='entity.parse.failed'))return res.status(400).json({error:'JSON tidak valid'});res.status(500).json({error:'Terjadi kesalahan pada server'})});module.exports=app;
